# Generated by Django 5.2.6 on 2025-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='docs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
